tap "nikitabobko/tap"
tap "FelixKratz/formulae"

cask "ghostty"
cask "obsidian"
cask "zed"
cask "flameshot"
cask "spotify"
cask "amethyst"
cask "ticktick"
cask "caffeine"
cask "vagrant"

brew "make"
brew "curl"
brew "coreutils"
brew "FelixKratz/formulae/sketchybar"
brew "jira-cli"
brew "libyaml"
brew "pkg-config"
brew "qemu"
brew "bash"
